[package]
name = "wasm-game-of-life"
version = "0.0.0"
authors = ["jens <jens@doellmann.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.83"

[dev-dependencies]
wasm-bindgen-test = "0.3.33"
